export interface Patient {
    name: string;
    appointmentType: string;
    status: "Active" | "Inactive";
    risk: "High" | "Medium" | "Low";

    referralDoctor: string;
    referralType: string;
}

export const dummyPatients: Patient[] = [
    {
        name: "Jane Doe",
        appointmentType: "Postpartum 4 week",
        status: "Active",
        risk: "High",
        referralDoctor: "Dr. Reyes",
        referralType: "Psychiatrist",
    },
    {
        name: "Anna Smith",
        appointmentType: "Consultation",
        status: "Inactive",
        risk: "Medium",
        referralDoctor: "Dr. Lim",
        referralType: "Nutritionist",
    },
    {
        name: "Mark Johnson",
        appointmentType: "Follow-up",
        status: "Active",
        risk: "Low",
        referralDoctor: "Dr. Lopez",
        referralType: "Cardiologist",
    },
    {
        name: "Emily Taylor",
        appointmentType: "Prenatal Visit",
        status: "Active",
        risk: "High",
        referralDoctor: "Dr. Gonzales",
        referralType: "OB-GYN",
    },
    {
        name: "Liam Brown",
        appointmentType: "Routine Check",
        status: "Inactive",
        risk: "Medium",
        referralDoctor: "Dr. Santos",
        referralType: "Pulmonologist",
    },
    {
        name: "Olivia Garcia",
        appointmentType: "New Patient",
        status: "Active",
        risk: "Low",
        referralDoctor: "Dr. Bautista",
        referralType: "Pediatrician",
    },
    {
        name: "Noah Martinez",
        appointmentType: "Postpartum 6 week",
        status: "Inactive",
        risk: "High",
        referralDoctor: "Dr. Ramos",
        referralType: "Psychiatrist",
    },
    {
        name: "Ava Hernandez",
        appointmentType: "Vaccination",
        status: "Active",
        risk: "Medium",
        referralDoctor: "Dr. Navarro",
        referralType: "Family Doctor",
    },
    {
        name: "William Wilson",
        appointmentType: "Dental Check",
        status: "Active",
        risk: "Low",
        referralDoctor: "Dr. De Vera",
        referralType: "Dentist",
    },
    {
        name: "Sophia Anderson",
        appointmentType: "Consultation",
        status: "Inactive",
        risk: "High",
        referralDoctor: "Dr. Javier",
        referralType: "Neurologist",
    },
    {
        name: "James Thomas",
        appointmentType: "Follow-up",
        status: "Active",
        risk: "Medium",
        referralDoctor: "Dr. Mendoza",
        referralType: "Orthopedic",
    },
    {
        name: "Mia Jackson",
        appointmentType: "Routine Check",
        status: "Active",
        risk: "Low",
        referralDoctor: "Dr. Fajardo",
        referralType: "Internist",
    },
    {
        name: "Benjamin White",
        appointmentType: "Postpartum 2 week",
        status: "Inactive",
        risk: "High",
        referralDoctor: "Dr. Tolentino",
        referralType: "Psychiatrist",
    },
    {
        name: "Charlotte Harris",
        appointmentType: "Prenatal Visit",
        status: "Active",
        risk: "Medium",
        referralDoctor: "Dr. Aquino",
        referralType: "OB-GYN",
    },
    {
        name: "Lucas Martin",
        appointmentType: "Consultation",
        status: "Inactive",
        risk: "Low",
        referralDoctor: "Dr. De Leon",
        referralType: "Nutritionist",
    },
    {
        name: "Amelia Thompson",
        appointmentType: "Vaccination",
        status: "Active",
        risk: "High",
        referralDoctor: "Dr. Santiago",
        referralType: "Pediatrician",
    },
    {
        name: "Henry Moore",
        appointmentType: "New Patient",
        status: "Inactive",
        risk: "Medium",
        referralDoctor: "Dr. Reyes",
        referralType: "Family Doctor",
    },
    {
        name: "Evelyn Taylor",
        appointmentType: "Follow-up",
        status: "Active",
        risk: "Low",
        referralDoctor: "Dr. Garcia",
        referralType: "Cardiologist",
    },
    {
        name: "Alexander Lee",
        appointmentType: "Dental Check",
        status: "Inactive",
        risk: "High",
        referralDoctor: "Dr. Soriano",
        referralType: "Dentist",
    },
    {
        name: "Harper Walker",
        appointmentType: "Prenatal Visit",
        status: "Active",
        risk: "Medium",
        referralDoctor: "Dr. Lim",
        referralType: "OB-GYN",
    },
    {
        name: "Daniel Young",
        appointmentType: "Consultation",
        status: "Active",
        risk: "Low",
        referralDoctor: "Dr. Abad",
        referralType: "Neurologist",
    },
    {
        name: "Elizabeth Allen",
        appointmentType: "Routine Check",
        status: "Inactive",
        risk: "High",
        referralDoctor: "Dr. Cruz",
        referralType: "Pulmonologist",
    },
    {
        name: "Matthew King",
        appointmentType: "Postpartum 4 week",
        status: "Active",
        risk: "Medium",
        referralDoctor: "Dr. Morales",
        referralType: "Psychiatrist",
    },
    {
        name: "Abigail Scott",
        appointmentType: "Vaccination",
        status: "Inactive",
        risk: "Low",
        referralDoctor: "Dr. Herrera",
        referralType: "Internist",
    },
    {
        name: "David Green",
        appointmentType: "Follow-up",
        status: "Active",
        risk: "High",
        referralDoctor: "Dr. Umali",
        referralType: "Orthopedic",
    },
    {
        name: "Ella Adams",
        appointmentType: "Consultation",
        status: "Inactive",
        risk: "Medium",
        referralDoctor: "Dr. Vergara",
        referralType: "Dentist",
    },
    {
        name: "Joseph Nelson",
        appointmentType: "New Patient",
        status: "Active",
        risk: "Low",
        referralDoctor: "Dr. Manalo",
        referralType: "Pediatrician",
    },
];
